name = "ghl-mcp-v2"
account_id = "203c62d7e81cfe8c46a8321623014797"
main = "src/index.ts"
compatibility_date = "2025-03-14"
compatibility_flags = ["nodejs_compat"]

[durable_objects]
bindings = [{ name = "MCP_OBJECT", class_name = "GHLMcpAgent" }]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["GHLMcpAgent"]

[[d1_databases]]
binding = "GHL_DB"
database_name = "ghl-accounts"
database_id = "647917a2-ace2-4b98-a10f-f822c5678646"

[[kv_namespaces]]
binding = "OAUTH_KV"
id = "ac787b89a4014510af5bf1e5e56f88f5"
